---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp1-svc-ingress
  annotations: 
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: myapp2.stepintolearning.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myapp1-svc
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp2-svc-ingress
  annotations: 
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: www.stepintolearning.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myapp2-svc
                port:
                  number: 80

